export const Years = ['2017', '2018', '2019'];
export const Levels = ['Curriculum Level 1',
                       'Curriculum Level 2',
                       'Curriculum Level 3',
                       'Curriculum Level 4',
                       'Curriculum Level 5',
                       'Curriculum Level 6',
                       'Curriculum Level 7',
                       'Curriculum Level 8'];
export const yearLevels = ['Year 9',
                           'Year 10',
                           'Year 11',
                           'Year 12',
                           'Year 13'];
export const Orientation = ['X', 'Y'];
export const Purpose = ['Descriptor', 'Qualifier'];
export const Ethnicity = [
 '211 Maori',
 '351 Tokelauan',
 '361 Fijian',
 '341 Niuean',
 '351 Tongan',
 '321 Cook Islands Maori',
 '311 Samoan',
 '371 Other Pacific Peoples',
 '411 Filipino',
 '412 Cambodian',
 '413 Vietnamese',
 '414 Other Southeast Asian',
 '431 Indian',
 '421 Chinese',
 '441 Sri Lankan',
 '442 Japanese',
 '443 Korean',
 '444 Other Asian',
 '511 Middle Eastern',
 '521 Latin American',
 '531 African',
 '611 Other Ethnicity',
 '999 Not Stated',
 '128 Australian',
 '121 British /Irish',
 '127 German',
 '122 Dutch',
 '123 Greek',
 '124 Polish',
 '125 South Slav',
 '126 Italian',
 '129 Other European',
 '111 NZ European/Pakeha'
];