import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatMenuModule,
         MatButton,
         MatButtonModule,
         MatToolbarModule,
         MatInputModule,
         MatAutocompleteModule,
         MatDialogModule,
         MatCardModule,
         MatSnackBarModule,
         MatTooltipModule,
         MatIconModule,
         MatListModule,
         MatSelectModule,
         MatSidenavModule,
         MatChipsModule,
         MatTabsModule,
         MatTableModule,
         MatRadioModule,
         MatExpansionModule,
         MatDatepickerModule,
         MatNativeDateModule } from '@angular/material';
import 'hammerjs';

@NgModule({
  imports: [
    CommonModule,
    MatMenuModule,
    MatButtonModule,
    MatToolbarModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatCardModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatIconModule,
    MatListModule,
    MatSelectModule,
    MatSidenavModule,
    MatChipsModule,
    MatTabsModule,
    MatTableModule,
    MatRadioModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatNativeDateModule,
  ],
  exports: [
    CommonModule,
    MatMenuModule,
    MatButtonModule,
    MatToolbarModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatCardModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatIconModule,
    MatListModule,
    MatSelectModule,
    MatSidenavModule,
    MatChipsModule,
    MatTabsModule,
    MatTableModule,
    MatRadioModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatNativeDateModule,
  ],
})
export class MyMaterialModule { }